from typing import Annotated, TypedDict
from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class GraphState(TypedDict):
    """Shared state passed between every node in the debate graph."""

    # ── Debate context (set once at match start) ─────────────────────────────
    topic: str         # The exact debate topic provided by the server
    stance: str        # "PRO" or "CON" — assigned by the server randomly
    our_team: str      # Our team name as known to the server (e.g. "team1")
    time_remaining: int  # Time remaining in the match in seconds

    # ── Per-turn inputs ───────────────────────────────────────────────────────
    opponent_message: str          # Latest argument received from the opponent
    message_history: list[str]     # Full chronological history of the debate

    # ── Researcher node output ─────────────────────────────────────────────────
    research_queries: list[str]    # Queries generated by the Researcher LLM
    search_results: list[dict]     # Raw results from Tavily: [{url, content}, ...]
    research_context: str          # Formatted plain-text context for the Debater

    # ── Debater node output ────────────────────────────────────────────────────
    final_argument: str            # Final debate text to send over WebSocket
